- type: dungeonConfig
  id: ShapeRoomTestBig
  layers:
  - !type:ShapeRoomDunGen
    areaSize: 150,150
    tile: Plating
    minRoomWidth: 5
    minRoomHeight: 5
    cutProb: 0.1 # Prefer more tunnels to large rooms
    outerWall: WallPlastitaniumIndestructible # there is no escape from the brig maintenance

  # Room roles
  - !type:RoomRoleDunGen
    minSize: 3,3
    maxSize: 6,6
    prob: 0.5
    weightsId: RoomMaintenanceSmall

  - !type:RoomRoleDunGen
    minSize: 6,6
    prob: 0.5
    weightsId: RoomMaintenanceMedium

  - !type:RoomRoleDunGen
    weightsId: RoomMaintenanceDefault # Fallback for all unassigned rooms

  - !type:WallMountDunGen
    contents: MaintenanceWalls
    tile: Plating

  # Walls and airlocks
  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: MaintenanceAirlock

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: Plating

  # Features
  - !type:FeatureDunGen
    feature:
      id: MaintenanceLight
      obstruct: false
      prob: 0.8
    position: !type:RoomRandomPosition

  - !type:FeatureDunGen
    feature:
      id: MaintenanceClosetLootRow
    rolls: 1, 2
    position: !type:RoomSidePosition
      availableSides:
      - Top
      - Bottom
      - Left
      - Right
    requireAll: false
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenance
    - !type:RoomRoleCondition
      role: RoomMaintenanceGenerator

  - !type:FeatureDunGen
    feature:
      id: MaintenanceGenerator
    position: !type:RoomSidePosition
      availableSides:
      - Center
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceGenerator

  - !type:FeatureDunGen
    feature:
      id: MaintenanceEngineeringLootRow
    rolls: 1, 2
    position: !type:RoomSidePosition
      availableSides:
      - Top
      - Bottom
      - Left
      - Right
      - Center # infinite loot theorem
    requireAll: false
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceEngineering

  - !type:FeatureDunGen
    feature:
      id: MaintenanceDormClosets
    position: !type:RoomSidePosition
      availableSides:
      - TopRight
      - BottomRight
      - Right
    requireAll: false
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceDorm

  - !type:FeatureDunGen
    feature:
      id: OfficeDecoration
    rolls: 1, 4
    position: !type:RoomSidePosition
      availableSides:
      - Top
      - Bottom
      - Left
      - Right
      - TopLeft
      - TopRight
      - BottomLeft
      - BottomRight
    requireAll: false
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceLibrary
    - !type:RoomRoleCondition
      role: RoomMaintenanceDorm

  - !type:FeatureDunGen
    feature:
      id: MaintenanceDormBed
    position: !type:RoomSidePosition
      availableSides:
      - Center
      - TopLeft
      - Left
      - BottomLeft
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceDorm

  - !type:FeatureDunGen
    feature:
      id: MaintenanceDormLight
    position: !type:RoomSidePosition
      availableSides:
      - Center
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceDorm

  - !type:FeatureDunGen
    feature:
      id: BookshelvesLine
    rolls: 1, 2
    position: !type:RoomRandomPosition
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceLibrary

  - !type:FeatureDunGen
    feature:
      id: ReadingTable
    position: !type:RoomRandomPosition
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceLibrary

  - !type:EntityTableDunGen
    minCount: 125
    maxCount: 180
    perDungeon: true
    ignoreReserved: true
    table:
      id: Girder

  - !type:EntityTableDunGen
    minCount: 100
    maxCount: 150
    perDungeon: true
    ignoreReserved: true
    table:
      id: ReinforcedGirder

  - !type:EntityTableDunGen
    minCount: 80
    maxCount: 120
    perDungeon: true
    ignoreReserved: true
    table:
      id: ReinforcedWindow

  - !type:EntityTableDunGen
    minCount: 150
    maxCount: 250
    perDungeon: true
    ignoreReserved: true
    table:
      id: Window

  # Loot

  - !type:EntityTableDunGen
    minCount: 750
    maxCount: 1500
    perDungeon: true
    ignoreReserved: true
    table: !type:NestedSelector
      tableId: GenericTrashItems

  - !type:EntityTableDunGen
    minCount: 500
    maxCount: 1000
    perDungeon: true
    ignoreReserved: true
    table: !type:NestedSelector
      tableId: SalvageScrapSpawnerCommon

  - !type:EntityTableDunGen
    minCount: 200
    maxCount: 300
    perDungeon: true
    ignoreReserved: true
    table: !type:NestedSelector
      tableId: SalvageScrapSpawnerValuable

  - !type:EntityTableDunGen
    minCount: 250
    maxCount: 400
    perDungeon: true
    ignoreReserved: true
    table: !type:NestedSelector
      tableId: SalvageTreasureSpawnerCommon

  - !type:EntityTableDunGen
    minCount: 100
    maxCount: 200
    perDungeon: true
    ignoreReserved: true
    table: !type:NestedSelector
      tableId: SalvageTreasureSpawnerValuable

  # Tiles
  - !type:FeatureFillDunGen
    feature:
      id: MaintenanceFloor
    requireAll: false
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenance
    - !type:RoomRoleCondition
      role: RoomMaintenanceGenerator

  - !type:FeatureFillDunGen
    feature:
      id: MaintenanceEngineeringFloor
    requireAll: false
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceEngineering

  - !type:FeatureFillDunGen
    feature:
      id: MaintenanceLibraryFloor
    requireAll: false
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceLibrary

  - !type:FeatureFillDunGen
    feature:
      id: MaintenanceDormFloor
    requireAll: false
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceDorm

  - !type:FeatureDunGen
    feature:
      id: MaintenanceDormCarpet
    position: !type:RoomSidePosition
      availableSides:
      - Center
    requireAll: false
    conditions:
    - !type:RoomRoleCondition
      role: RoomMaintenanceDorm

  # Other

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  # TODO auto cabling is very bad for performance because of how node groups work
  #- !type:AutoCablingDunGen
  #  entity: CableMV
  #  nodeGroup: MVPower

  #- !type:AutoCablingDunGen
  #  entity: CableHV
  #  nodeGroup: HVPower

  #- !type:FeatureFillDunGen
  #  feature:
  #    id: MaintenanceCatwalk

- type: entityTable
  id: MaintenanceAirlock
  table: !type:AllSelector
    children:
    - id: AirlockMaintAlwaysPowered
    - id: Firelock
      prob: 0.5

- type: entityTable
  id: MaintenanceWalls
  table: !type:GroupSelector
    children:
    - id: RandomPosterAny
    - id: ExtinguisherCabinetFilled
      prob: 0.1
    - id: RandomPainting
      prob: 0.01

- type: weightedRandom
  id: RoomMaintenanceSmall
  weights:
    #RoomMaintenanceArcade: 2
    #RoomMaintenanceAtmos: 1
    #RoomMaintenanceBotany: 2
    #RoomMaintenanceChem: 1
    RoomMaintenanceDorm: 1
    RoomMaintenanceEngineering: 2
    #RoomMaintenanceKitchen: 1
    #RoomMaintenanceSurgery: 1
    #RoomMaintenanceMedical: 1
    #RoomMaintenancePrison: 1
    RoomMaintenanceGenerator: 2

- type: weightedRandom
  id: RoomMaintenanceMedium
  weights:
    RoomMaintenanceLibrary: 2
    #RoomMaintenanceScience: 1
    #RoomMaintenanceBar: 1

- type: weightedRandom
  id: RoomMaintenanceDefault
  weights:
    RoomMaintenance: 1
